server:
  port: 8899
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playgrounds?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql


  jackson:
    serialization:
      INDENT_OUTPUT: true

flyway:
  locations: classpath:/flyway
  encoding: utf8

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
api:
  path: /api